### ISSUE TITLE
Should we really use the name useTry?

### ISSUE THREAD

**Issue by mohsinulhaq** [Coly010/no-try#20]
Can a function be called a hook just because it's returning an array?
Because of the naming,
- eslint will now show irrelevant lint info on it, and not allow it to be called conditionally.
- it implies that it's to be used inside functional components, but in reality, it could be used literally anywhere.

**Comment by Coly010** [comment]
That very much seems like an issue with eslint. If it's assuming that any function that starts with the word `use` is a React Hook, then there's a bigger issue there to deal with.

I'm not sure how the name implies it should be used in functional components, this isn't targeted at React. Like you said, this can be used anywhere.

**Comment by mohsinulhaq** [comment]
Then why are we introducing the `useTry` export instead of `noTry`? It seems very much inspired by React hooks, which are render-only functions.

**Comment by mohsinulhaq** [comment]
Besides, it's not even using any React hook internally, nor does it do any closure storage to get the latest state value like useState and others. So if it's not intended to be a hook, we should refrain from using the `use` prefix.

Found this to be relevant to our issue:
https://github.com/facebook/react/issues/15227

**Comment by Coly010** [comment]
We are using `useTry` because under the hood, the function is still using a try-catch. We're just abstracting it away, we are still _using_ try-catch.

A developer coming along to a piece of code containing this library, seeing `noTry` without prior knowledge of the library, will add cognitive load to understand what the piece of code is actually doing. `useTry` is much less complex and a lot easier to get a quick understanding of what's happening.

React do not, and cannot, own a prefix for functions. That is simply outrageous. The problem here lies in the `eslint-plugin-react-hooks` and how they are determining what a React Hook is.

Other non-React libraries may also be using the `use` prefix, as highlighted by the issue you attached. 

If you are having an issue with `eslint` regarding the usage of this library as a React Hook you have 3 options:

 - Use the `noTry` export. It still exists, and you can use it safely.
 - Use in-line eslint disable `// eslint-disable-next-line react-hooks/rules-of-hooks`
 - Configure eslint to not run on the files that you are using `useTry` with.

**Comment by mohsinulhaq** [comment]
fair enough, thanks @Coly010 🙂
